name: Docker build & push

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download needed files
        run: |
          mkdir -p ./src/lab1
          curl -fSL -o ./src/lab1/gol-template.s https://github.com/Patrick-Pataky/cs200_docker/releases/latest/download/gol-template.s
          curl -fSL -o ./src/lab1/project.tar.gz https://github.com/Patrick-Pataky/cs200_docker/releases/latest/download/project.tar.gz
          ls
          ls ./src

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          load: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/cs200:latest
